/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haiersmart_smartsale_JniPir */

#ifndef _Included_com_haiersmart_smartsale_JniPir
#define _Included_com_haiersmart_smartsale_JniPir
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haiersmart_smartsale_JniPir
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_haiersmart_smartsale_JniPir_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_haiersmart_smartsale_JniPir
 * Method:    openGpioDev
 * Signature: ()I
 */
JNIEXPORT jobject JNICALL Java_com_haiersmart_smartsale_JniPir_openGpioDev
  (JNIEnv *, jobject);

/*
 * Class:     com_haiersmart_smartsale_JniPir
 * Method:    closeGpioDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_haiersmart_smartsale_JniPir_closeGpioDev
  (JNIEnv *, jobject);

/*
 * Class:     com_haiersmart_smartsale_JniPir
 * Method:    getGpio
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_haiersmart_smartsale_JniPir_getGpio
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_haiersmart_smartsale_JniPir
 * Method:    releaseGpio
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_haiersmart_smartsale_JniPir_releaseGpio
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_haiersmart_smartsale_JniPir
 * Method:    setGpioState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_haiersmart_smartsale_JniPir_setGpioState
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
